name: Ansible workflow using Poetry to manage dependencies

on:
  push:
    branches:
      - main

env:
  POETRY_VERSION: "1.8.3"

jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python
        id: setup_python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml # Read python version from a file pyproject.toml
          cache: poetry # caching poetry dependencies

      - name: Cache Poetry binary
        uses: actions/cache@v4
        with:
          path: ~/.cache/poetry-${{ env.POETRY_VERSION }}
          key: poetry-binary-cache-${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-${{ env.POETRY_VERSION }}
      - name: Install Poetry ${{ env.POETRY_VERSION }}
        run: |
          export POETRY_HOME="${HOME}/.cache/poetry-${POETRY_VERSION}"
          python3 -m venv "${POETRY_HOME}"
          "${POETRY_HOME}/bin/pip" install "poetry==${POETRY_VERSION}"

          "${POETRY_HOME}/bin/poetry" --version

          echo "${POETRY_HOME}/bin/" >> "${GITHUB_PATH}"

      - name: Install dependencies with Poetry
        run: |
          poetry install
      - name: List dependencies
        run: poetry show
